### ISSUE TITLE
The simulator leaks JAX traces

### ISSUE THREAD

**Issue by diegoferigo** [ami-iit/jaxsim#43]
After the major jax update merged in #38, compiling in jit some method raises [`jax.errors.UnexpectedTracerError`](https://jax.readthedocs.io/en/latest/errors.html#jax.errors.UnexpectedTracerError). Probably recent version of jax became more picky about it.

It's worth noting that the computation is correct if the methods are not jit-compiled. The leak error occurs only when a jax transformation is applied.

A MRE is the following:

```python
import pathlib

import robot_descriptions.double_pendulum_description

import jax
import jaxsim
from jaxsim.simulation.ode_integration import IntegratorType
from jaxsim.simulation.simulator import VelRepr

sim = jaxsim.JaxSim.build(
    step_size=0.001,
    steps_per_run=1,
    velocity_representation=VelRepr.Inertial,
    integrator_type=IntegratorType.EulerSemiImplicit,
).mutable(mutable=True, validate=False)

urdf_model = pathlib.Path(robot_descriptions.double_pendulum_description.URDF_PATH)

model = sim.insert_model_from_description(model_description=urdf_model)

# The problem occurs only if we jit-compile the method
sim.step = jax.jit(sim.step)

step_data = sim.step()

print(step_data)
```

<details>
<summary>Error</summary>

```

jaxsim on  main via 🐍 v3.10.12 🅒 /jaxsim  
✦ ❯ JAX_CHECK_TRACER_LEAKS=1 python /tmp/mre.py
jaxsim[109057] INFO Enabling JAX to use 64bit precision
Initialized persistent compilation cache at /tmp/jaxsim_compilation_cache
jaxsim[109057] DEBUG Using JAX compilation cache located at '/tmp/jaxsim_compilation_cache'
/jaxsim/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/jaxsim/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
jaxsim[109057] DEBUG Found model '2dof_planar' in SDF resource
jaxsim[109057] DEBUG Model '2dof_planar' is floating-base
jaxsim[109057] DEBUG Considering 'base_link' as base link
jaxsim[109057] INFO The kinematic graph doesn't need to be reduced
Traceback (most recent call last):
  File "/tmp/mre.py", line 24, in <module>
    step_data = sim.step()
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/pjit.py", line 249, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/api.py", line 301, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/pjit.py", line 498, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/pjit.py", line 960, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/linear_util.py", line 345, in memoized_fun
    ans = call(fun, *args)
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/pjit.py", line 913, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2148, in trace_to_jaxpr_dynamic
    with core.new_main(DynamicJaxprTrace, dynamic=True) as main:  # type: ignore
  File "/jaxsim/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/jaxsim/lib/python3.10/site-packages/jax/_src/core.py", line 1081, in new_main
    if leaked_tracers: raise leaked_tracer_error("trace", t(), leaked_tracers)
jax._src.traceback_util.UnfilteredStackTrace: Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(uint64[])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/simulation/simulator.py:383 (step)
<DynamicJaxprTracer 139813065845040> is referred to by <SimulatorData 139817522022624>.time_ns
<SimulatorData 139817522022624> is referred to by <JaxSim 139814809360256>.data
<JaxSim 139814809360256> is referred to by __main__.sim

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067483920> is referred to by <PhysicsModelState 139813065717696>.joint_positions
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067485680> is referred to by <PhysicsModelState 139813065717696>.joint_velocities
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067487280> is referred to by <PhysicsModelState 139813065717696>.base_position
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[4])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067488800> is referred to by <PhysicsModelState 139813065717696>.base_quaternion
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813065655056> is referred to by <PhysicsModelState 139813065717696>.base_linear_velocity
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813065659536> is referred to by <PhysicsModelState 139813065717696>.base_angular_velocity
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1248 (integrate)
<DynamicJaxprTracer 139813065666896> is referred to by <PhysicsModelInput 139812935597744>.tau
<PhysicsModelInput 139812935597744> is referred to by <ModelData 139812935015520>.model_input
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3,6])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1248 (integrate)
<DynamicJaxprTracer 139813065668176> is referred to by <PhysicsModelInput 139812935597744>.f_ext
<PhysicsModelInput 139812935597744> is referred to by <ModelData 139812935015520>.model_input
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3,0])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1244 (<lambda>)
<DynamicJaxprTracer 139813065665616> is referred to by <SoftContactsState 139813067048032>.tangential_deformation
<SoftContactsState 139813067048032> is referred to by <ModelData 139812935015520>.contact_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/mre.py", line 24, in <module>
    step_data = sim.step()
  File "/jaxsim/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(uint64[])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/simulation/simulator.py:383 (step)
<DynamicJaxprTracer 139813065845040> is referred to by <SimulatorData 139817522022624>.time_ns
<SimulatorData 139817522022624> is referred to by <JaxSim 139814809360256>.data
<JaxSim 139814809360256> is referred to by __main__.sim

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067483920> is referred to by <PhysicsModelState 139813065717696>.joint_positions
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067485680> is referred to by <PhysicsModelState 139813065717696>.joint_velocities
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067487280> is referred to by <PhysicsModelState 139813065717696>.base_position
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[4])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813067488800> is referred to by <PhysicsModelState 139813065717696>.base_quaternion
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813065655056> is referred to by <PhysicsModelState 139813065717696>.base_linear_velocity
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1241 (<lambda>)
<DynamicJaxprTracer 139813065659536> is referred to by <PhysicsModelState 139813065717696>.base_angular_velocity
<PhysicsModelState 139813065717696> is referred to by <ModelData 139812935015520>.model_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[2])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1248 (integrate)
<DynamicJaxprTracer 139813065666896> is referred to by <PhysicsModelInput 139812935597744>.tau
<PhysicsModelInput 139812935597744> is referred to by <ModelData 139812935015520>.model_input
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3,6])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1248 (integrate)
<DynamicJaxprTracer 139813065668176> is referred to by <PhysicsModelInput 139812935597744>.f_ext
<PhysicsModelInput 139812935597744> is referred to by <ModelData 139812935015520>.model_input
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model

Traced<ShapedArray(float64[3,0])>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /home/dferigo/git/jaxsim/src/jaxsim/high_level/model.py:1244 (<lambda>)
<DynamicJaxprTracer 139813065665616> is referred to by <SoftContactsState 139813067048032>.tangential_deformation
<SoftContactsState 139813067048032> is referred to by <ModelData 139812935015520>.contact_state
<ModelData 139812935015520> is referred to by <Model 139813066856944>.data
<Model 139813066856944> is referred to by __main__.model
```

</details>

We follow a pattern in which we have classes treated as pytrees (that can be therefore treated as non-static arguments of transformed functions, including `self`). These classes have as attributes their data (e.g. `SimulatorData`, `ModelData`, etc.) and as methods the algorithms (e.g. `JaxSim.step`, `Model.free_floating_mass_matrix`, etc.).

This has worked fine so far, but I fear that recent jax became more picky when propagating traces on `*Data` objecs that are stored within our classes. The sofware design we followed gave us so far the freedom to expose an OO approach while not preventing a more jax-idiomatic functional approach. Maybe we should start rethinking it, or find a proper workaround.

**Comment by diegoferigo** [comment]
We managed to work around this issue by introducing [new decorators](https://github.com/ami-iit/jaxsim/blob/72e130abd1fee0644feccfbe12d2e51f73891aa2/src/jaxsim/utils/oop.py#L17-L20) to apply over class methods. 

Since all our [`high_level`](https://github.com/ami-iit/jaxsim/tree/v0.1/src/jaxsim/high_level) classes are PyTrees, the `self` argument of their methods is compatible with `jax.jit`. The main idea behind these new decorators is transforming the following method call that update attributes of `self` (i.e. a r/w method):

```python
out = obj.method(self, *args, **kwargs)
```

with the following equivalent functional call:

```python
out, obj_updated = wrapper(obj.method, *args, **kwargs)
```

Then, the fields of `obj_updated` are moved into `obj`.

In this way, we can jit-compile the wrapped method without risking to leak traces inside `self`.

This was the gist of the trace leak solution. However, the new decorators do much more, like auto-enabling jit and vmap transformations, treat differently r/o and r/w methods to catch earlier errors during development, automatically handle the mutability of `jax_dataclasses` objects, etc . For more details, refer to #44 and #48.
